package com.paymentgateway.model.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Stores UPI-specific details for a UPI payment transaction.
 *
 * <p>Linked to {@link Transaction} via FK on {@code transaction_id} (composition pattern).</p>
 */
@Entity
@Table(name = "upi_payment_details",
        indexes = {
                @Index(name = "idx_upi_details_txn_id", columnList = "transaction_id", unique = true),
                @Index(name = "idx_upi_details_vpa",    columnList = "vpa")
        })
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UpiPaymentDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** FK back to the parent transaction. One UPI record per transaction. */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "transaction_id", referencedColumnName = "transaction_id", nullable = false)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Transaction transaction;

    /**
     * Virtual Payment Address (VPA) used for this transaction.
     * Format: {@code username@bankhandle} (e.g. {@code rajesh@okaxis}).
     */
    @Column(name = "vpa", nullable = false, length = 128)
    private String vpa;

    /**
     * Bank handle extracted from the VPA (the part after '@').
     * Used to identify which bank the payer's UPI account belongs to.
     */
    @Column(name = "bank_handle", nullable = false, length = 64)
    private String bankHandle;

    /**
     * Internal UPI transaction reference ID generated by the gateway simulator.
     * In a production system this would be the NPCI reference ID.
     */
    @Column(name = "upi_txn_ref_id", nullable = false, length = 64)
    private String upiTxnRefId;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
