package com.ecommerce.order.enums;

public enum OrderState {
	CREATED, INVENTORY_RESERVING, INVENTORY_RESERVED,
    PAYMENT_PROCESSING, PAYMENT_CONFIRMED,
    FULFILMENT_STARTED, COMPLETED,
    INVENTORY_RESERVE_FAILED, PAYMENT_FAILED, CANCELLED
}
